name: GitOps-Demo CI 

on: push

jobs:
  open_pull_request:
    if: contains( github.ref, 'release') #developブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repository: hgaiji/gitops-k8smanifest
          path: manifest
      - name: update k8s manifest
        run: | 
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/release/##g") 
          yq eval ".spec.template.spec.containers[0].image=\"hoge:$IMAGE_TAG\"" './manifest/staging/deployment.yaml'
          cat ./manifest/staging/deployment.yaml