name: GitOps-Demo CI 

on: push
env: # global環境変数を設定
  DOCKER_IMAGE_NAME: gitopsapp

jobs:
  push_docker_image:
    if: contains( github.ref, 'release') #developブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME -f ./Dockerfile . 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image to GitHub Container Registry
        run: |  
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/release/v##g") 
            docker tag $DOCKER_IMAGE_NAME ghcr.io/${{ github.repository_owner }}/$DOCKER_IMAGE_NAME:$IMAGE_TAG
            docker push ghcr.io/${{ github.repository_owner }}/$DOCKER_IMAGE_NAME:$IMAGE_TAG