name: GitOps-Demo CI 

on: push
env: # global環境変数を設定
  DOCKER_IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  CR_NAME: ${{ secrets.CONTAINER_REGISTORY_NAME }}
  CR_USER: ${{ secrets.CONTAINER_REGISTORY_USER }}

jobs:
  push_docker_image:
    if: contains( github.ref, 'release') #developブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME -f ./docker/Dockerfile . 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTORY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image to Container Registry
        run: |  
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/release/##g")
            IMAGE_NAME_WITH_CR="${CR_NAME}/${CR_USER}/${DOCKER_IMAGE_NAME}:${IMAGE_TAG}"
            docker tag $DOCKER_IMAGE_NAME "${IMAGE_NAME_WITH_CR}"
            docker push "${IMAGE_NAME_WITH_CR}"